export interface ApiRoute {
  name: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  description?: string;
  authenticated?: boolean;
  body?: unknown;
}

export interface RouteManifest { routes: ApiRoute[] }

export function createPostmanCollection(applicationName: string, manifest: RouteManifest): Record<string, unknown> {
  if (!applicationName.trim()) throw new Error("Application name is required for Postman generation.");
  if (!Array.isArray(manifest.routes)) throw new Error("routes/manifest.json must contain a routes array.");
  const item = manifest.routes.map((route) => {
    if (!route.name || !route.path.startsWith("/") || !["GET", "POST", "PUT", "PATCH", "DELETE"].includes(route.method)) throw new Error("Every API route requires a name, supported method, and absolute path.");
    const requestPath = route.path.replace(/:([A-Za-z][A-Za-z0-9_]*)/g, "{{$1}}");
    const headers: { key: string; value: string; type: string }[] = [
      { key: "X-Tenant-ID", value: "{{tenantId}}", type: "text" },
      { key: "Accept", value: "application/json", type: "text" }
    ];
    if (route.body !== undefined) headers.push({ key: "Content-Type", value: "application/json", type: "text" });
    if (route.authenticated) headers.push({ key: "Authorization", value: "Bearer {{accessToken}}", type: "text" });
    return {
      name: route.name,
      request: {
        method: route.method,
        header: headers,
        ...(route.body === undefined ? {} : { body: { mode: "raw", raw: JSON.stringify(route.body, null, 2), options: { raw: { language: "json" } } } }),
        url: { raw: `{{baseUrl}}${requestPath}`, host: ["{{baseUrl}}"], path: requestPath.split("/").filter(Boolean) },
        description: route.description ?? ""
      }
    };
  });
  return {
    info: {
      name: `${applicationName} API`,
      description: "Generated by Zolt from routes/manifest.json. Regenerate with `zolt postman`.",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    variable: [
      { key: "baseUrl", value: "http://localhost:3000" },
      { key: "tenantId", value: "default" },
      { key: "accessToken", value: "" }
    ],
    item
  };
}
